routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resources([
    'practices' => 'PracticeController',
    'employees' => 'EmployeeController',
    'fieldsofpractice' => 'FieldOfPracticeController'
]);

app/Practice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;

/**
 * @property int id
 * @property string logo
 * @property string name
 * @property Collection fieldsOfPractice
 * @property Collection employees
 */
class Practice extends Model
{
    protected $table = 'practices';

    protected $fillable = ['name', 'email', 'logo', 'website'];

    public function fieldsOfPractice()
    {
        return $this->belongsToMany(FieldOfPractice::class, 'practice_field_of_practice');
    }

    public function employees()
    {
        return $this->hasMany(Employee::class);
    }
}

app/Http/Controllers/PracticeController.php
<?php

namespace App\Http\Controllers;

use App\Employee;
use App\FieldOfPractice;
use App\Http\Requests\PracticeRequest;
use App\Practice;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Storage;

class PracticeController extends Controller
{
    /**
     * PracticeController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(): Response
    {
        $practices = Practice::paginate(10);

        return \response()->view('practices.index', compact('practices'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(): Response
    {
        $employees = Employee::all();
        $fieldsofpractice = FieldOfPractice::all();
        return \response()->view('practices.create', compact('employees', 'fieldsofpractice'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param PracticeRequest $request
     * @return RedirectResponse
     */
    public function store(PracticeRequest $request): RedirectResponse
    {
        $data = $request->except('_token');
//        dd($request->all());
        $path = '';
        if ($request->file('logo')->isValid())
        {
            $path = 'storage/' . $request->logo->store('logos', 'public');
        }

        $data['logo'] = $path;

        /** @var Practice $practice */
        $practice = Practice::create($data);

        $practice->fieldsOfPractice()->sync($data['tags']);

        return redirect()->route('practices.index')->with('info_message', "Practice '$practice->name' successfully added.");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Practice  $practice
     * @return \Illuminate\Http\Response
     */
    public function show(Practice $practice): Response
    {
        return \response()->view('practices.show', compact('practice'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Practice  $practice
     * @return \Illuminate\Http\Response
     */
    public function edit(Practice $practice): Response
    {
        $employees = ['NONE' => null] + Employee::select(['id', \DB::raw('CONCAT(first_name, \' \', last_name) as name')])->get()->pluck('id', 'name')->toArray();
        $fieldsofpractice = ['NONE' => null] + FieldOfPractice::all()->pluck('id', 'tag')->toArray();

//        dd($fieldsofpractice);

        $owningTags = $practice->fieldsOfPractice->pluck('id')->toArray();
        $owningEmployees = $practice->employees->pluck('id')->toArray();

        return \response()->view('practices.edit',
            compact('practice', 'employees', 'fieldsofpractice', 'owningTags', 'owningEmployees')
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param PracticeRequest $request
     * @param  \App\Practice $practice
     * @return RedirectResponse
     */
    public function update(PracticeRequest $request, Practice $practice): RedirectResponse
    {
        $data = $request->except('_token');
//        dd($request->all());
        if ($request->has('logo') && $request->file('logo')->isValid())
        {
            // TODO: Fix
            $logoPathSplit = explode('/', $practice->logo);
            if (count($logoPathSplit) > 0)
            {
                Storage::disk('public')->delete('/' . $practice->logo /**logoPathSplit[count($logoPathSplit) - 1]*/);
            }

            $data['logo'] = 'storage/' . $request->logo->store('logos', 'public');
        }
        else
        {
            unset($data['logo']);
        }

        $practice->update($data);

        if (isset($data['tags']))
        {
            $practice->fieldsOfPractice()->sync(\in_array(null, $data['tags']) ? [] : $data['tags']);
        }

//        if (isset($data['employees']))
//        {
//            $practice->employees()->update($data['employees']);
////            $practice->employees()->saveMany(\in_array(null, $data['employees']) ? [] : Employee::where('id', $data['employees']));
//        }

        return redirect()->route('practices.index')->with('info_message', "Practice '$practice->name' successfully edited.");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Practice $practice
     * @return RedirectResponse
     */
    public function destroy(Practice $practice): RedirectResponse
    {
        // TODO: Fix logo delete
        Storage::disk('public')->delete(explode('/', $practice->logo)[2]);
        Practice::destroy($practice->id);
        return redirect()->route('practices.index')->with('info_message', "Practice #$practice->id deleted successfully");
    }
}

resources/views/practices/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="px-5">
        <h1 class="text-center mb-4">Create New Practice</h1>
        <form method="POST" action="{{ route('practices.store') }}" enctype="multipart/form-data">
            @csrf
            @include('practices.form')
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/practices/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="px-5">
        <h1 class="text-center mb-4">Edit Practice #{{ $practice->id }}</h1>
        <form method="POST" action="{{ route('practices.update', $practice->id) }}" enctype="multipart/form-data">
            @csrf
            {{ method_field('PUT') }}
            @include('practices.form')
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/practices/form.blade.php
<div class="form-row">
    <div class="form-group col-md-6">
        <label for="name">Name</label>
        <input name="name" type="text" class="form-control @error('name') is-invalid @enderror" id="name"
               value="{{ isset($practice) ? $practice->name : old('name') }}">
        @if ($errors->has('name'))
            <div class="invalid-feedback">
                @foreach($errors->get('name') as $message)
                    {{ $message }} <br>
                @endforeach
            </div>
        @endif
    </div>
    <div class="form-group col-md-6">
        <label for="email">Email</label>
        <input name="email" type="email" class="form-control @error('email') is-invalid @enderror" id="email"
               value="{{ isset($practice) ? $practice->email : old('email') }}">
        @if ($errors->has('email'))
            <div class="invalid-feedback">
                @foreach($errors->get('email') as $message)
                    {{ $message }} <br>
                @endforeach
            </div>
        @endif
    </div>
</div>
<div class="form-row">
    <div class="form-group col-md-6">
        <label for="website">Website</label>
        <input name="website" type="url" class="form-control" id="website" value="{{ isset($practice) ? $practice->website : old('website') }}">
    </div>
    <div class="form-group {{ isset($practice) ? 'col-md-3' : 'col-md-6' }}">
        <label for="logo">Logo</label>
        <input name="logo" type="file" class="form-control-file @error('logo') is-invalid @enderror" id="logo">
        @if ($errors->has('logo'))
            <div class="invalid-feedback">
                Logo must be at least 100x100
            </div>
        @endif
    </div>
    @if(isset($practice) && $practice->logo !== '')
        <div class="form-group col-md-3">
            <label for="current-logo">Current Logo</label>
            <img src="{{ Str::startsWith($practice->logo, 'http') ? $practice->logo : url('/') . '/' . $practice->logo }}" class="img-thumbnail" height="100" width="100">
        </div>
    @endif
</div>

<div class="form-row">
    <div class="form-group col-md-6">
        <label for="tags">Fields of practice</label>
        <select multiple class="form-control" id="tags" name="tags[]" size="10">
            @foreach($fieldsofpractice as $tag => $id)
                <option value="{{ $id }}" @if (isset($practice) && \in_array($id, $owningTags)) selected @endif>{{ $tag }}</option>
            @endforeach
        </select>
    </div>
    @isset ($practice)
        <div class="form-group col-md-6">
            <label for="employees">Employees</label>
            <select multiple class="form-control" id="employees" name="employees[]" size="10" readonly>
                @foreach($employees as $employee => $id)
                    <option value="{{ $id }}" @if(\in_array($id, $owningEmployees)) selected @endif>{{ $employee }}</option>
                @endforeach
            </select>
        </div>
    @endisset
</div>

resources/views/practices/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="px-5">
        <div class="d-flex justify-content-between mb-4">
            <a href="{{ route('practices.create') }}" class="btn btn-success btn-lg" title="Add New Practice">
                Add New Practice
            </a>
            {{ $practices->links() }}
        </div>
        <div class="table-responsive">
            <table class="table table-stripped">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Logo</th>
                    <th scope="col">Website</th>
                    {{--<th scope="col">Created at</th>--}}
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($practices as $practice)
                    <tr>
                        <th scope="row">{{ $practice->id }}</th>
                        <td>{{ $practice->name }}</td>
                        <td>{{ $practice->email }}</td>
                        <td><img src="{{ Str::startsWith($practice->logo, 'http') ? $practice->logo : url('/') . '/' . $practice->logo }}" class="img-thumbnail" width="100" height="100"></td>
                        <td><a href="{{ $practice->website }}">{{ Str::limit($practice->website, 20) }} </a></td>
                        {{--<td>{{ $practice->created_at }}</td>--}}
                        <td class="btn-group-">
                            <a href="{{ route('practices.show', $practice->id) }}" class="btn btn-success btn-sm">View</a>
                            <a href="{{ route('practices.edit', $practice->id) }}" class="btn btn-primary btn-sm">Edit</a>
                            <form method="post" action="{{ route('practices.destroy', $practice->id) }}" style="display:inline">
                                @csrf
                                {{ method_field('DELETE') }}
                                <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Confirm delete?')">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div class="d-flex justify-content-center">
            {{ $practices->links() }}
        </div>

    </div>
@endsection

resources/views/practices/show.blade.php
@extends('layouts.app')
@section('content')

    <div class="px-5">
        <div class="d-flex justify-content-start">
            <a href="{{ route('practices.edit', $practice->id) }}" class="btn btn-primary">Edit</a>
            &nbsp;
            <form method="post" action="{{ route('practices.destroy', $practice->id) }}">
                @csrf
                {{ method_field('DELETE') }}
                <button class="btn btn-danger" type="submit" onclick="return confirm('Confirm delete?')">Delete</button>
            </form>
        </div>
        <br>

        <div class="table-responsive">
            <table class="table table-stripped">
                <tbody>
                <tr>
                    <th scope="row">ID</th>
                    <th>{{ $practice->id }}</th>
                </tr>
                <tr>
                    <th scope="row">Name</th>
                    <th>{{ $practice->name }}</th>
                </tr>
                <tr>
                    <th scope="row">Email</th>
                    <th>{{ $practice->email }}</th>
                </tr>
                <tr>
                    <th scope="row">Website</th>
                    <th><a href="{{ $practice->website }}">{{ $practice->website }}</a></th>
                </tr>
                <tr>
                    <th scope="row">Created_at</th>
                    <th>{{ $practice->created_at }}</th>
                </tr>
                <tr>
                    <th scope="row">Updated at</th>
                    <th>{{ $practice->updated_at }}</th>
                </tr>
                <tr>
                    <th scope="row">Logo</th>
                    <th><img src="{{ $practice->logo }}" class="img-fluid" alt="Responsive image"></th>
                </tr>
                </tbody>
            </table>

        </div>
    </div>
@endsection