routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resources([
    'practices' => 'PracticeController',
    'employees' => 'EmployeeController',
    'fieldsofpractice' => 'FieldOfPracticeController'
]);

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * @property int id
 */
class Employee extends Model
{
    protected $fillable = ['first_name', 'last_name', 'practice_id', 'email', 'phone'];

    protected $table = 'employees';

    public function practice()
    {
        return $this->belongsTo(Practice::class);
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Employee;
use App\Http\Requests\EmployeeRequest;
use App\Practice;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * EmployeeController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::paginate(10);

        return response()->view('employees.index', compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $practices = ['NONE' => null] + Practice::all()->pluck('id', 'name')->toArray();
        return response()->view('employees.create', compact('practices'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param EmployeeRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeRequest $request)
    {
        $data = $request->except('_token');

        Employee::create($data);

        return redirect()->route('employees.index')->with('info_message', 'New employee successfully created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        return response()->view('employees.show', compact('employee'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        $practices = ['NONE' => null] + Practice::all()->pluck('id', 'name')->toArray();
        return response()->view('employees.edit', compact('employee', 'practices'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param EmployeeRequest $request
     * @param  \App\Employee $employee
     * @return \Illuminate\Http\Response
     */
    public function update(EmployeeRequest $request, Employee $employee)
    {
        $data = $request->except('_token');

        $employee->update($data);

        return redirect()->route('employees.index')->with('info_message', 'Employee successfully updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $message = 'Employee successfully deleted.';
        if (Employee::destroy($employee->id) == 0)
        {
            $message = 'Something went wrong. Employee couldn\'t be deleted.';
        }

        return redirect()->route('employees.index')->with('info_message', $message);
    }
}

resources/views/employees/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="px-5">
        <h1 class="text-center mb-4">Create New Employee</h1>
        <form method="POST" action="{{ route('employees.store') }}" enctype="multipart/form-data">
            @csrf
            @include('employees.form')
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/employees/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="px-5">
        <h1 class="text-center mb-4">Edit Practice #{{ $employee->id }}</h1>
        <form method="POST" action="{{ route('employees.update', $employee->id) }}" enctype="multipart/form-data">
            @csrf
            {{ method_field('PUT') }}
            @include('employees.form')
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/employees/form.blade.php
<div class="form-row">
    <div class="form-group col-md-6">
        <label for="first_name">First Name</label>
        <input name="first_name" type="text" class="form-control @error('first_name') is-invalid @enderror" id="first_name"
               value="{{ isset($employee) ? $employee->first_name : old('first_name') }}">
        @if ($errors->has('first_name'))
            <div class="invalid-feedback">
                @foreach($errors->get('first_name') as $message)
                    {{ $message }} <br>
                @endforeach
            </div>
        @endif
    </div>
    <div class="form-group col-md-6">
        <label for="last_name">Last Name</label>
        <input name="last_name" type="text" class="form-control @error('last_name') is-invalid @enderror" id="last_name"
               value="{{ isset($employee) ? $employee->last_name : old('last_name') }}">
        @if ($errors->has('last_name'))
            <div class="invalid-feedback">
                @foreach($errors->get('last_name') as $message)
                    {{ $message }} <br>
                @endforeach
            </div>
        @endif
    </div>
</div>
<div class="form-row">
    <div class="form-group col-md-6">
        <label for="email">Email</label>
        <input name="email" type="email" class="form-control" id="email"
               value="{{ isset($employee) ? $employee->email : old('email') }}">
    </div>
    <div class="form-group col-md-6">
        <label for="phone">Phone</label>
        <input name="phone" type="tel" class="form-control" id="phone"
               value="{{ isset($employee) ? $employee->phone : old('phone') }}">
    </div>
</div>

<div class="form-row">
    <div class="form-group col-md-6">
        <label for="practice_id">Practice</label>
        <select class="form-control @error('practice_id') is-invalid @enderror" id="practice_id" name="practice_id">
            @foreach($practices as $name => $id)
                <option value="{{ $id }}" @if (isset($employee) && $employee->practice && $id === $employee->practice->id) selected @endif>{{ $name }}</option>
            @endforeach
        </select>
        @if ($errors->has('practice_id'))
            <div class="invalid-feedback">
                @foreach($errors->get('practice_id') as $message)
                    {{ $message }} <br>
                @endforeach
            </div>
        @endif
    </div>
</div>

resources/views/employees/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="px-5">
        <div class="d-flex justify-content-between mb-4">
            <a href="{{ route('employees.create') }}" class="btn btn-success btn-lg" title="Add New Employee">
                Add New Employee
            </a>
            {{ $employees->links() }}
        </div>
        <div class="table-responsive">
            <table class="table table-stripped">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Practice</th>
                        <th scope="col">Email</th>
                        <th scope="col">Phone</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($employees as $employee)
                    <tr>
                        <th scope="row">{{ $employee->id }}</th>
                        <td>{{ $employee->first_name }}</td>
                        <td>{{ $employee->last_name }}</td>
                        <td>
                            @if ($employee->practice)
                                <a href="{{ route('practices.show', $employee->practice->id) }}">{{ $employee->practice->name }} </a>
                            @else
                            /
                            @endif
                        </td>
                        <td>{{ $employee->email }}</td>
                        <td>{{ $employee->phone }}</td>
                        <td class="btn-group-">
                            <a href="{{ route('employees.show', $employee->id) }}" class="btn btn-success btn-sm">View</a>
                            <a href="{{ route('employees.edit', $employee->id) }}" class="btn btn-primary btn-sm">Edit</a>
                            <form method="post" action="{{ route('employees.destroy', $employee->id) }}" style="display:inline">
                                @csrf
                                {{ method_field('DELETE') }}
                                <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Confirm delete?')">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div class="d-flex justify-content-center">
            {{ $employees->links() }}
        </div>

    </div>
@endsection

resources/views/employees/show.blade.php
@extends('layouts.app')
@section('content')

    <div class="px-5">
        <div class="d-flex justify-content-start">
            <a href="{{ route('employees.edit', $employee->id) }}" class="btn btn-primary">Edit</a>
            &nbsp;
            <form method="post" action="{{ route('employees.destroy', $employee->id) }}">
                @csrf
                {{ method_field('DELETE') }}
                <button class="btn btn-danger" type="submit" onclick="return confirm('Confirm delete?')">Delete</button>
            </form>
        </div>
        <br>

        <div class="table-responsive">
            <table class="table table-stripped">
                <tbody>
                    <tr>
                        <th scope="row">ID</th>
                        <th>{{ $employee->id }}</th>
                    </tr>
                    <tr>
                        <th scope="row">First Name</th>
                        <th>{{ $employee->first_name }}</th>
                    </tr>
                    <tr>
                        <th scope="row">Last Name</th>
                        <th>{{ $employee->last_name }}</th>
                    </tr>
                    <tr>
                        <th scope="row">Practice</th>
                        <th>
                            @if ($employee->practice)
                                <a href="{{ route('practices.show', $employee->practice->id) }}">{{ $employee->practice->name }} </a>
                            @else
                                /
                            @endif
                        </th>
                    </tr>
                    <tr>
                        <th scope="row">Email</th>
                        <th>{{ $employee->email }}</th>
                    </tr>
                    <tr>
                        <th scope="row">Created_at</th>
                        <th>{{ $employee->created_at }}</th>
                    </tr>
                    <tr>
                        <th scope="row">Updated at</th>
                        <th>{{ $employee->updated_at }}</th>
                    </tr>
                </tbody>
            </table>

        </div>
    </div>
@endsection